import React from 'react'

const Skills = () => {
  return (
    <div id='skills' >
        <h1>Skills</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nulla, facilis porro minima veniam iure magni adipisci aperiam dolor, eveniet enim nobis blanditiis necessitatibus laudantium accusamus, excepturi similique hic tempora illo nam vero consectetur alias qui exercitationem! Modi, dicta adipisci? Voluptatum eligendi nisi esse numquam? Harum molestias temporibus voluptatem alias, culpa fugiat fuga quod? Earum eligendi ea, assumenda ad dolor nihil impedit optio, iusto, facere quaerat tempora vitae doloremque. Laborum quas ex at ratione placeat porro perspiciatis accusamus impedit pariatur dolor possimus tempore, consectetur ut et cumque, dolorum illo temporibus illum dignissimos sit ad. Minus cumque porro unde impedit magni ea minima eius, necessitatibus veniam accusantium voluptate? Saepe quis maiores esse nulla repellat suscipit. Animi, nostrum amet debitis esse officiis modi sunt unde molestiae? Reprehenderit dignissimos distinctio asperiores cupiditate sunt ab ut atque, eveniet architecto quis similique repellendus, nihil nobis molestiae eaque a quisquam minus quaerat impedit quod consectetur illo. Cumque obcaecati aperiam et illum a esse, illo velit ex fugit accusamus corrupti tenetur vitae deleniti. Tempora voluptatem culpa eum, architecto magni cupiditate autem, alias officiis vero sequi harum! Repellat laudantium culpa, voluptatem sit illum totam corporis velit quisquam error fuga? Rem quas tempore ducimus soluta dolore vel labore culpa aut, reprehenderit cum temporibus distinctio, magnam ipsum aliquid corporis expedita obcaecati ad dolores fugiat ipsam? Enim nobis a iste dolorem quos pariatur fuga, qui velit ipsam doloribus reprehenderit, delectus nam autem alias deserunt illo molestias nihil dignissimos veniam soluta accusamus! Corporis illum ipsa accusamus officiis ducimus enim fugit quo, deserunt doloremque, vitae, quis recusandae perferendis. Placeat repellendus quod natus exercitationem. Ducimus quos repellat porro a atque est, eos vel omnis. Quaerat sit, qui quod accusamus neque ullam maxime dignissimos hic provident nulla ex ratione inventore unde placeat libero incidunt aliquam at. Ab dolorum reprehenderit laboriosam tempora necessitatibus culpa quisquam rem, odit voluptatum eaque nisi. Tenetur, a? Non odit suscipit, dolorum repellendus perspiciatis dolore blanditiis deleniti tempore nihil repellat natus possimus qui in maiores nemo voluptas quo sequi minus! Quaerat aliquid commodi repellat culpa doloremque qui sapiente saepe quisquam esse. Quae, repudiandae iste facere sit impedit laborum quos ea pariatur! Sapiente iure id accusantium ipsam pariatur non labore, similique nobis aliquid laudantium expedita nisi atque debitis amet dolore recusandae distinctio delectus? Consequatur quas eligendi atque fugit perferendis voluptates ad repudiandae soluta, quisquam natus deleniti! Eveniet mollitia ratione ipsam assumenda, accusantium odit error magni quaerat temporibus quisquam commodi unde voluptas maiores fugiat!</p>
    </div>
  )
}

export default Skills